version: "3.3"

services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    ports:
      - "127.0.0.1:8080:8080"
    command: "--es-url=http://es:9200/"
  generator:
    build: generator
    environment:
      BACKFILL: "1"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
